project:
  type: website

website:
  title: "smwindecker.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-link: true

execute:
  freeze: auto


